DemoMVC/DemoMVC/Controllers/ChequesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DemoMVC.Domain.Data;
using DemoMVC.Domain.Repository;
using DemoSite.Library.Services;
using DemoSite.Library.Helpers;
using DemoSite.Library.Dependency;

namespace DemoMVC.Controllers
{
    public class ChequesController : Controller
    {
        IKenticoDB _entities;

        public ChequesController()
        {
            _entities = new KenticoDB();
        }

        public ChequesController(IKenticoDB entities)
        {
            _entities = entities;
        }

        // GET: Cheques
        public ActionResult Index()
        {
            IChequeRepository repo = new ChequeRepository(_entities);
            var cheques = repo.GetCheques(); 
            return View(cheques);
        }

        public ActionResult Detail(int id)
        {
            DependencyServiceFactory<ChequeService> factory = new DependencyServiceFactory<ChequeService>();

            var cheque = factory.GetService().GetChequeDetail(id);
            return View(cheque);
        }

        [ChildActionOnly]
        public ActionResult Top3()
        {
            IChequeRepository repo = new ChequeRepository(_entities);

            var cheques = repo.GetCheques();

            var top3Cheques = (from c in cheques
                               orderby c.ChequeAmount descending
                               select c).Take(3).ToList();

            return PartialView("_Top3", top3Cheques);
        }
    }
}

DemoMVC/DemoMVC/Views/Cheques/Detail.cshtml
@model DemoMVC.Domain.Model.Cheque
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table">
    <tr>
        <th>Name</th><td>@Model.ChequeDetail.ChequeName</td>
    </tr>
    <tr>
        <th>Date</th>
        <td>@Model.ChequeDetail.ChequeDate.ToString("dd/MM/yyyy")</td>
    </tr>
    <tr>
        <th>Amount</th>
        <td>$@Model.ChequeDetail.ChequeAmount.ToString("#,##0.00")</td>
    </tr>
    <tr>
        <th>Text</th>
        <td>@Model.ChequeText</td>
    </tr>
</table>
@Html.ActionLink("Back to List", "Index")
<div>
    @Html.Action("Top3", "Cheques")

</div>

DemoMVC/DemoMVC/Views/Cheques/Index.cshtml
@model List<DemoMVC.Domain.Data.custom_cheque>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "Cheques";
}

<table class="table">
    <tr><th>Name</th><th>Date</th><th>Amount</th></tr>
    @foreach (var cheque in Model)
    {
        <tr>
            <td>@Html.ActionLink(@cheque.ChequeName, "Detail", new { id = @cheque.ChequeID }, null)</td>
            <td>@cheque.ChequeDate.ToString("dd/MM/yyyy")</td>
            <td>$@cheque.ChequeAmount.ToString("#,##0.00")</td>
        </tr>
    }
</table>

<div>
    @Html.Action("Top3", "Cheques")

</div>

DemoMVC/DemoMVC/Views/Cheques/_Top3.cshtml
@model IList<DemoMVC.Domain.Data.custom_cheque>

<h3>Top 3 cheques (Partial View)</h3>
<ul>
    @foreach (var cheque in Model)
    {
        <li>@cheque.ChequeName - @cheque.ChequeAmount.ToString("#,##0.00")</li>
    }
</ul>